---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-app
  namespace: default
  labels:
    app: production-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
        - name: production-app
          image: napeno/production:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: production-app-service
  namespace: default
  labels:
    app: production-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: production-app
