version: '3.8'
services:
  db:
    image: mysql:8.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      - MYSQL_DATABASE=web_cv
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - '3308:3306'
    expose:
      - 3308
  kafka:
    image: docker.io/bitnami/kafka:3.8
    ports:
      - "9092:9092"
      - "9093:9093"  # Exposing the controller port
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # Corrected advertised listeners
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092

      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092

      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Add the required advertised host name
      # - KAFKA_ADVERTISED_HOST_NAME=host.docker.internal  
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1  

  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3308
      - DB_HOSTNAME = "http://localhost"
      - DB_DATABASE = web_cv
      - REACT_URL=localhost
      - DB_PASSWORD = 123
      - DB_USERNAME = root
      # - REACT_USERNAME =root
      # - REACT_PASSWORD =123
      - DB_DIALECT = mysql
      - DB_HOSTNAME=host.docker.internal
      - KAFKA_BROKER=kafka:9092  # Thay đổi ở đây

    ports:
      - 5000:5000
  nginx:
    image: nginx:1.25.4
    ports:
      - 80:80
    volumes:
      - ../my-app/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
volumes:
  kafka_data:
    driver: local
