apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-stable
  labels:
    app: frontend
    version: stable
spec:
  replicas: {{ .Values.replicaCount.stable }}
  selector:
    matchLabels:
      app: frontend
      version: stable
  template:
    metadata:
      labels:
        app: frontend
        version: stable
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.repository }}:{{ .Values.image.stableTag }}
          ports:
            - containerPort: 80
