apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "frontend.fullname" . }}-destination
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  host: {{ include "frontend.fullname" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
