apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-rollout
  labels:
    app: frontend-rollout
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      steps:
{{ toYaml .Values.rollout.strategy.canary.steps | indent 8 }}
  selector:
    matchLabels:
      app: frontend-rollout
  template:
    metadata:
      labels:
        app: frontend-rollout
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
