replicaCount: 2

image:
  repository: napeno/backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false  # Mặc định là false nếu không sử dụng ingress
  className: ""
  annotations: {}
  tls: []
  hosts:
    - host: "example.com"
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources: {}
